class_names:
- person
- car
- motorcycle
- pet
data:
  train:
    ann_path: /home/ubuntu/Workspace/datasets/object_detection/fisheye_5class/mix_det/annotations/train_4class.json
    img_path: /home/ubuntu/Workspace/datasets/object_detection/BDD100k/bdd100k/images/100k/train/
    input_size:
    - 320
    - 260
    keep_ratio: false
    name: CocoDataset
    pipeline:
      brightness: 0.2
      contrast:
      - 0.6
      - 1.4
      flip: 0.5
      normalize:
      - - 103.53
        - 116.28
        - 123.675
      - - 57.375
        - 57.12
        - 58.395
      perspective: 0.0
      rotation: 0
      saturation:
      - 0.5
      - 1.2
      scale:
      - 0.6
      - 1.4
      shear: 0
      stretch:
      - - 0.8
        - 1.2
      - - 0.8
        - 1.2
      translate: 0.2
  val:
    ann_path: /home/ubuntu/Workspace/datasets/object_detection/fisheye_5class/mix_det/annotations/val_3class.json
    img_path: /home/ubuntu/Workspace/datasets/woodscape/rgb_images/
    input_size:
    - 320
    - 260
    keep_ratio: false
    name: CocoDataset
    pipeline:
      normalize:
      - - 103.53
        - 116.28
        - 123.675
      - - 57.375
        - 57.12
        - 58.395
device:
  batchsize_per_gpu: 64
  gpu_ids:
  - 1
  - 2
  - 3
  workers_per_gpu: 4
distill: {}
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP
grad_clip: 35
log:
  interval: 50
model:
  arch:
    aux_head:
      activation: LeakyReLU
      feat_channels: 160
      input_channel: 160
      name: SimpleConvHead
      num_classes: 4
      reg_max: 7
      stacked_convs: 4
      strides:
      - 8
      - 16
      - 32
      - 64
    backbone:
      act: lrelu
      depth: 0.33
      depthwise: true
      name: ConvNext
      width: 0.25
    detach_epoch: 5
    fpn:
      activation: LeakyReLU
      in_channels:
      - 96
      - 192
      - 384
      kernel_size: 5
      name: GhostPAN
      num_extra_level: 1
      out_channels: 80
      use_depthwise: true
    head:
      activation: LeakyReLU
      feat_channels: 80
      input_channel: 80
      kernel_size: 5
      loss:
        loss_bbox:
          loss_weight: 2.0
          name: GIoULoss
        loss_dfl:
          loss_weight: 0.25
          name: DistributionFocalLoss
        loss_qfl:
          beta: 2.0
          loss_weight: 1.0
          name: QualityFocalLoss
          use_sigmoid: true
      name: NanoDetPlusHead
      norm_cfg:
        type: BN
      num_classes: 4
      reg_max: 7
      stacked_convs: 2
      strides:
      - 8
      - 16
      - 32
      - 64
    name: NanoDetPlus
  weight_averager:
    decay: 0.9998
    name: ExpMovingAverager
save_dir: ./nanodet-plus-m_416-fisheye_4class_convnext_11_08
schedule:
  load_model: /home/ubuntu/Workspace/toandev/Pretrain_od/nanodet/checkpoints/nanodet-plus-m_416_3class_darknet_20_06/model_best/model_best.ckpt
  lr_schedule:
    T_max: 40
    eta_min: 5.0e-05
    name: CosineAnnealingLR
  optimizer:
    lr: 0.0005
    name: AdamW
    weight_decay: 0.05
  resume: null
  total_epochs: 40
  val_intervals: 2
  warmup:
    name: linear
    ratio: 0.0001
    steps: 500
teacher_model:
  arch:
    backbone: {}
    fpn: {}
    head: {}
test: {}
