# nanodet-EfficientNet-Lite0_320
# COCO mAP(0.5:0.95) = 0.247
#             AP_50  = 0.404
#             AP_75  = 0.250
#           AP_small = 0.079
#               AP_m = 0.243
#               AP_l = 0.406
save_dir: workspace/efficient0_512-fisheye-distill
model:
  arch:
    name: OneStageDetector
    backbone:
      name: EfficientNetLite
      model_name: efficientnet_lite0
      out_stages: [2,4,6]
      activation: ReLU6
    fpn:
      name: PAN
      in_channels: [40, 112, 320]
      out_channels: 64
      start_level: 0
      num_outs: 3
    head:
      name: NanoDetPlusHead
      num_classes: 3
      input_channel: 64
      feat_channels: 64
      stacked_convs: 2
      kernel_size: 5
      strides: [8, 16, 32]
      activation: LeakyReLU
      reg_max: 10
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0
    # Auxiliary head, only use in training time.
    aux_head:
      name: SimpleConvHead
      num_classes: 3
      input_channel: 512
      feat_channels: 512
      stacked_convs: 4
      strides: [8, 16, 32]
      activation: LeakyReLU
      reg_max: 10
data:
  train:
    name: CocoDataset
    img_path: /home/ubuntu/Workspace/datasets/od/fisheye_5class/
    ann_path: /home/ubuntu/Workspace/datasets/od/fisheye_5class/coco_assistants/mix_det/ws_fs_train_merged.json
    image_size: [1280,800] #[w,h]
    input_size: [512,512] #[w,h]
    keep_ratio: True
    pipeline:
      perspective: 0.0
      scale: [0.6, 1.4]
      stretch: [[1, 1], [1, 1]]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [0.6, 1.4]
      saturation: [0.5, 1.2]
      normalize: [[127.0, 127.0, 127.0], [128.0, 128.0, 128.0]]
  val:
    name: CocoDataset
    img_path: /home/ubuntu/Workspace/datasets/od/fisheye_5class/
    ann_path: /home/ubuntu/Workspace/datasets/od/fisheye_5class/coco_assistants/mix_det/ws_fs_val_merged.json
    image_size: [1280,800] #[w,h]
    input_size: [512,512] #[w,h]
    keep_ratio: True
    pipeline:
      normalize: [[127.0, 127.0, 127.0], [128.0, 128.0, 128.0]]
device:
  gpu_ids: [0,1,2,3]
  workers_per_gpu: 4
  batchsize_per_gpu: 64
schedule:
  resume:
  #  load_model: YOUR_MODEL_PATH
  load_model: pretrained/nanodet-EfficientNet-Lite0_320.ckpt
  optimizer:
    name: SGD
    lr: 0.05
    momentum: 0.9
    weight_decay: 0.0001
  warmup:
    name: linear
    steps: 500
    ratio: 0.01
  total_epochs: 190
  lr_schedule:
    name: MultiStepLR
    milestones: [140,170,180,185]
    gamma: 0.1
  val_intervals: 20
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP

log:
  interval: 10

class_names: ['person', 'vehicles', 'motocycle']
